# Generated by Django 3.2.3 on 2021-05-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuoyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utc_timestamp', models.DateTimeField(blank=True, null=True)),
                ('significant_wave_height', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('swell_height', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('swell_period', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('wind_wave_height', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('wind_wave_period', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('swell_direction', models.CharField(blank=True, max_length=3, null=True)),
                ('wind_wave_direction', models.CharField(blank=True, max_length=3, null=True)),
                ('wind_steepness', models.CharField(blank=True, max_length=10, null=True)),
                ('average_wave_period', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('dominant_wave_agerage_direction', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SurfSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='SANDS_BEACH', max_length=20)),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('buoyID', models.CharField(default='46054', max_length=5)),
            ],
        ),
    ]
