# Generated by Django 3.2.3 on 2021-05-16 22:48

from django.db import migrations

def create_data(apps, schema_editor):
    SurfSpot = apps.get_model('surfspots', 'SurfSpot')
    SurfSpot(name = "SurfSpot01", location = "SurfLocation01", buoyID = "1").save()

class Migration(migrations.Migration):

    dependencies = [
        ('surfspots', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
