# Generated by Django 3.2.3 on 2021-05-16 22=48

from django.db import migrations

def create_data(apps, schema_editor):
    BuoyData = apps.get_model('surfspots', 'SurfSpot')
    BuoyData(
        utc_timestamp="2021-05-11T01:40:00+00:00",
        significant_wave_height= 2.5,
        swell_height= 2.4,
        swell_period= 10.8, 
        wind_wave_height= 0.9, 
        wind_wave_period= 5.0, 
        swell_direction= "WNW",
        wind_wave_direction= "W", 
        wind_steepness= "SWELL", 
        average_wave_period= 7.1, 
        dominant_wave_agerage_direction= 302.0
    ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('surfspots', '0002_SurfSpot'),
    ]

    operations = [
        migrations.RunPython(create_data)
    ]
